# Generated by Django 5.1.1 on 2024-10-02 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcial2App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
